### ISSUE TITLE
Closing Gui throws NullPointerException

### ISSUE THREAD

**Issue by sunnapu** [umlet/umlet#335]
I use UMLet version 13.3 June 2015

Open a uxf file in Umlet such as:
```
umlet.sh Dom.uxf 
```
1. The file is open

2. Click the close X button, it throws NullPointerException, and Gui is not closed unless I press Ctrl-C in console to exit the program.

``` Java
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at com.baselet.control.config.Config.getOpenFileHome(Config.java:75)
	at com.baselet.control.config.handler.ConfigHandler.saveConfig(ConfigHandler.java:182)
	at com.baselet.control.Main.closeProgram(Main.java:419)
	at com.baselet.gui.standalone.StandaloneGUI.closeWindow(StandaloneGUI.java:72)
	at com.baselet.gui.standalone.SwingWindowListener.windowClosing(SwingWindowListener.java:19)
	at java.awt.Window.processWindowEvent(Window.java:2058)
	at javax.swing.JFrame.processWindowEvent(JFrame.java:297)
	at java.awt.Window.processEvent(Window.java:2017)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by afdia** [comment]
Can you please try it again with v14.1.1?
This looks like is a config dir issue and we have introduced OS specific cfg dirs in v14, therefore it's possible that the issue is fixed already
Thanks!

**Comment by sunnapu** [comment]
I installed v14.1.1, and found the same issue, when I click the close X button.
```
$ umlet.sh Sleep.uxf
log4j:WARN No appenders could be found for logger (com.baselet.control.enums.Program).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at com.baselet.control.config.Config.getOpenFileHome(Config.java:75)
	at com.baselet.control.config.handler.ConfigHandler.saveConfig(ConfigHandler.java:165)
	at com.baselet.control.Main.closeProgram(Main.java:174)
	at com.baselet.standalone.gui.StandaloneGUI.closeWindow(StandaloneGUI.java:79)
	at com.baselet.standalone.gui.SwingWindowListener.windowClosing(SwingWindowListener.java:19)
	at java.awt.Window.processWindowEvent(Window.java:2058)
	at javax.swing.JFrame.processWindowEvent(JFrame.java:297)
	at java.awt.Window.processEvent(Window.java:2017)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I use ctrl-c to exit the program.
If I want to open the program again, the program exits this time without opening file.
```
$ umlet.sh Sleep.uxf
log4j:WARN No appenders could be found for logger (com.baselet.control.enums.Program).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

**Comment by sunnapu** [comment]
Sorry, I accidentally close this issue, it should still remain open.

**Comment by afdia** [comment]
please check your umlet.cfg file for the one line starting with "open_file_home=" and post the content here (for me to debug it)

afterwards delete the line and check if the bug disappears

**Comment by sunnapu** [comment]
I use Mac. I found the cfg file at ./Library/Preferences/UMLet/umlet.cfg.
It will be created every time I run 'umlet.sh'. And it is an empty file.

I don't have ~/.config/UMLet/ directory.

**Comment by afdia** [comment]
I cannot reproduce the issue on my machine (even if I create an empty umlet.cfg file

I have built an UMLet version which adds some additional checks and prints information to the console when the relevant code is accessed.
Please download it here: https://www.dropbox.com/s/0ip7i5vehmlxpt9/umlet-standalone-14.1.1.zip?dl=0

Start the application, open any uxf file and close the application. Afterwards please tell me the lines it has written to the console and check if the bug is still present (it should be fixed)

Thanks!

**Comment by sunnapu** [comment]
This issue is fixed in v14.2.0-SNAPSHOT. Thank you very much.

**Comment by afdia** [comment]
Good to hear! :)

That means that the issue can be easily fixed, but I still don't know the exact source of the error (I've tried 2 changes in this SNAPSHOT build)
Also I don't know if the last open directory gets remembered correctly, therefore could you please:

1. Start UMLet 14.2.0-SNAPSHOT, use "File -> Open" to open a file, stop UMLet.
What is the console output of UMLet? (should be several lines with "TRYING TO SET ..." or "GETTING ..."

2. After closing UMLet start it again and use "File -> Open". Has it remembered the last open location or does the dialogue always start at your users home directory?
And perhaps also post the console output of UMLet.

Thanks for your help!

**Comment by sunnapu** [comment]
1. Start UMLet 14.2.0-SNAPSHOT, use "File -> Open" to open a file, stop UMLet.
What is the console output of UMLet? (should be several lines with "TRYING TO SET ..." or "GETTING ..."
```
$ umlet.sh
log4j:WARN No appenders could be found for logger (com.baselet.control.enums.Program).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
GETTING /Users/benefit/_gitrepo/courses-ready/course-java/java6-course/src/main/java/tp/java6/l070/thread/demo1/influencescheduler
SETTING /Users/benefit/_gitrepo/courses-ready/course-java/java6-course/src/main/java/tp/java6/l070/thread/demo1/influencescheduler
GETTING /Users/benefit/_gitrepo/courses-ready/course-java/java6-course/src/main/java/tp/java6/l070/thread/demo1/influencescheduler
TRYING TO SET /Users/benefit/_gitrepo/courses-ready/course-java/java6-course/src/main/java/tp/java6/l070/thread/demo1/influencescheduler///Users/benefit/_gitrepo/courses-ready/course-java/java6-course/src/main/java/tp/java6/l070/thread/demo1/influencescheduler
SETTING /Users/benefit/_gitrepo/courses-ready/course-java/java6-course/src/main/java/tp/java6/l070/thread/demo1/influencescheduler

#### before close Umlet, the console outputs the following line
GETTING /Users/benefit/_gitrepo/courses-ready/course-java/java6-course/src/main/java/tp/java6/l070/thread/demo1/influencescheduler
```

2. After closing UMLet start it again and use "File -> Open". Has it remembered the last open location or does the dialogue always start at your users home directory?
And perhaps also post the console output of UMLet.
```
$ umlet.sh
log4j:WARN No appenders could be found for logger (com.baselet.control.enums.Program).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
GETTING /Users/benefit/_gitrepo/courses-ready/course-java/java6-course/src/main/java/tp/java6/l070/thread/demo1/influencescheduler
SETTING /Users/benefit/_gitrepo/courses-ready/course-java/java6-course/src/main/java/tp/java6/l070/thread/demo1/influencescheduler
GETTING /Users/benefit/_gitrepo/courses-ready/course-java/java6-course/src/main/java/tp/java6/l070/thread/demo1/influencescheduler
TRYING TO SET /Users/benefit/_gitrepo/courses-ready/course-java/java6-course/src/main/java/tp/java6/l070/thread/demo1/influencescheduler///Users/benefit/_gitrepo/courses-ready/course-java/java6-course/src/main/java/tp/java6/l070/thread/demo1/influencescheduler
SETTING /Users/benefit/_gitrepo/courses-ready/course-java/java6-course/src/main/java/tp/java6/l070/thread/demo1/influencescheduler
```

Yes, it remembered, smart enough! Thanks.

**Comment by afdia** [comment]
Thanks, it will be fixed in the next release.

The output looks like it was an issue with your specific umlet.cfg file though, so perhaps you can use UMLet 14.1.1 without an issue (because the SNAPSHOT version should have fixed the umlet.cfg entry for you)
